version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: proyectoFinal
    #restart: always
    depends_on:
      - db
    ports:
      - 8000:8000
      # - 80:80
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    volumes: 
      - ./:/app

  db:
    image: mariadb
    container_name: proyectoFinal-db
    #restart: always
    environment:
      MYSQL_DATABASE: proyectofinal
      MYSQL_USER: proyectofinaluser
      MYSQL_PASSWORD: "admin1234"
      MYSQL_ROOT_PASSWORD: admin1234
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3310:3306
 
volumes:
  db:    

