# Generated by Django 4.1.7 on 2023-05-06 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=100)),
                ('limite_presupuestario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.proyecto')),
            ],
        ),
    ]
