# Generated by Django 4.1.6 on 2023-05-08 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_remove_proyecto_id_proyecto_proveedor_and_more'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentabancaria',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='proveedor',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='proyecto.proyecto',
                verbose_name='Proyecto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
