# Generated by Django 4.1.6 on 2023-05-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_remove_cuentabancaria_proyecto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentabancaria',
            old_name='proveedor',
            new_name='proyecto',
        ),
    ]
