# Generated by Django 4.1.6 on 2023-05-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_rename_proveedor_cuentabancaria_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentabancaria',
            name='id',
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='idcuenta',
            field=models.CharField(
                default=1,
                max_length=8,
                primary_key=True,
                serialize=False,
                verbose_name='ID cuenta'),
            preserve_default=False,
        ),
    ]
