# Generated by Django 4.1.6 on 2024-06-01 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_remove_cuentabancaria_id_cuentabancaria_idcuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='limite_presupuestario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
