# Generated by Django 4.1.6 on 2023-05-24 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0004_alter_proyecto_duracion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costos',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('descripcion',
                 models.CharField(
                     max_length=100)),
                ('costo',
                 models.DecimalField(
                     decimal_places=2,
                     max_digits=10)),
                ('presupuesto',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.DO_NOTHING,
                     to='proyecto.proyecto',
                     verbose_name='Presupuesto')),
            ],
        ),
    ]
