# Generated by Django 4.1.6 on 2023-05-25 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_alter_proyecto_duracion_and_more'),
        ('costos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costos',
            name='presupuesto',
        ),
        migrations.AddField(
            model_name='costos',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='proyecto.proyecto', verbose_name='Proyecto'),
            preserve_default=False,
        ),
    ]
