# Generated by Django 4.1.6 on 2023-05-25 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_alter_proyecto_duracion_and_more'),
        ('costos', '0002_remove_costos_presupuesto_costos_proyecto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costos',
            new_name='Costo',
        ),
    ]
