# Generated by Django 4.1.6 on 2023-05-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0003_rename_costos_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costo',
            name='descripcion',
            field=models.TextField(max_length=255),
        ),
    ]
