# Generated by Django 4.1.6 on 2023-05-30 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_alter_proyecto_duracion'),
        ('costos', '0004_alter_costo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costo',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto', verbose_name='Proyecto'),
        ),
    ]
