# Generated by Django 4.1.6 on 2023-05-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('num_proyecto', models.CharField(
                    max_length=8, verbose_name='NUM Proyecto')),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('objetivo', models.CharField(max_length=255)),
                ('presupuesto', models.CharField(max_length=15)),
                ('duracion', models.DecimalField(
                    decimal_places=2, max_digits=78)),
                ('responsables', models.CharField(max_length=200)),
            ],
        ),
    ]
