# Generated by Django 4.1.6 on 2023-05-08 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='id',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='proveedores.proveedor', verbose_name='Proveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='num_proyecto',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='NUM Proyecto'),
        ),
    ]
