# Generated by Django 4.1.6 on 2023-05-10 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
        ('proyecto', '0002_remove_proyecto_id_proyecto_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='proveedor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='proveedores.proveedor',
                verbose_name='Proveedor'),
        ),
    ]
