# Generated by Django 4.1.6 on 2023-05-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_alter_proyecto_duracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='duracion',
            field=models.DecimalField(decimal_places=0, max_digits=1, verbose_name='Duracion (Meses)'),
        ),
    ]
