# Generated by Django 4.1.6 on 2023-05-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_alter_proyecto_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='duracion',
            field=models.CharField(
                max_length=100, verbose_name='Duracion (Meses)'),
        ),
    ]
