# Generated by Django 4.1.6 on 2024-05-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_alter_proyecto_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='duracion',
            field=models.IntegerField(verbose_name='Duracion (Meses)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='objetivo',
            field=models.TextField(verbose_name='Objetivo'),
        ),
    ]
