# Generated by Django 4.1.6 on 2024-05-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_alter_proyecto_duracion_alter_proyecto_objetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='duracion',
            field=models.TextField(verbose_name='Duracion (Meses)'),
        ),
    ]
