# Generated by Django 4.1.6 on 2024-06-01 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_alter_proyecto_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='duracion',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Duracion (Meses)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='presupuesto',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)], verbose_name='Presupuesto ($)'),
        ),
    ]
