# Generated by Django 4.1.6 on 2023-05-04 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='proveedores.estado', verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, verbose_name='R.F.C')),
                ('razon_social', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('estado', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='proveedores.estado', verbose_name='Estado')),
                ('municipio', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='proveedores.municipio', verbose_name='Municipio')),
            ],
        ),
    ]
